### ISSUE TITLE
[ionic v4] ionic cordova run android fails (to load resources) with any fresh starter template

### ISSUE THREAD

**Issue by somq** [ionic-team/starters#451] opened 2018-09-11 10:59 UTC
**Starter Type:**  angular
**Starter Template:**  blank, side-menu & tabs

**Description:**

Running ```ionic cordova run android``` in a freshly generated starter template folder will show a blank page on any device.

Using chrome *remote devices* tool it appears it fails to load resources:
```
runtime.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
12:47:54.936 styles.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
12:47:54.936 polyfills.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
12:47:54.938 vendor.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
12:47:54.938 cordova.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
12:47:54.940 main.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
12:47:55.021 /assets/icon/favicon.png:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
```

**My `ionic info`:**

```
$ ionic info
√ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)          : 4.1.2 (C:\Users\xxx\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.8
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : android 6.3.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.3, (and 4 other plugins)

System:

   NodeJS : v9.9.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.1.0
   OS     : Windows 7
```
**How to reproduce:**
```sh
ionic start i4-sidemenu sidemenu --type=angular
cd i4-sidemenu
ionic cordova prepare android
ionic cordova run android --verbose
```

**Other Information:**

A *base path* change fixes the issue but it seems to break angular router navigation.
```<base href="." />```

Note: It works with ```--live-reload```: the device is able to reach the files through the network.

**Comment by SmallProgramIndustry** [comment] 2018-09-25 09:41
me too You don't solve

**Comment by dwieeb** [comment] 2018-09-25 16:07
Is it using `http://localhost:8080`?

**Comment by somq** [comment] 2018-09-25 16:51
URL shown using DevTools with no ```--live-reload``` option is ```file:///android_asset/www/index.html```
I'm seeing the same url with v3, but the path is valid in this case.

**Comment by dwieeb** [comment] 2018-09-25 18:05
That would be the issue. The new Web View plugin uses an HTTP server. Maybe there's a configuration issue. Can I see your `config.xml`?

**Comment by somq** [comment] 2018-09-25 20:00
This is the default one generated with a fresh template.
Here is the one-liner: ```ionic start i4-sidemenu sidemenu --type=angular && cd i4-sidemenu && ionic cordova prepare android && code . && ionic cordova run android --verbose```

I guess this is what you wanted to confirm ```<allow-intent href="http://*/*" />```

ionic 4 config.xml is exactly the same as the ionic 3 one by the way.

I made a gist with the whole config.xml
https://gist.github.com/somq/fca1747dfe1177bfdbe4f806ce764e6d

**Comment by dwieeb** [comment] 2018-09-25 21:27
Thanks, that looks correct. I don't have this issue with new apps. I am trying to narrow down what's wrong. 

This is the URL loaded by the web view for me:

<img width="535" alt="image" src="https://user-images.githubusercontent.com/236501/46043903-e4480d00-c0de-11e8-8d3b-09b01f884467.png">

**Comment by somq** [comment] 2018-09-25 21:50
I can tell that I'm having the issue on 2 computers and 2 differents phones (Android 6 & 7).

Here is the logcat trace if it can help:
https://gist.github.com/somq/443dc265d95252a347a590c5258ccdd3

I this issue related?: https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/175

I could test on other devices tomorrow at work.

**Comment by SmallProgramIndustry** [comment] 2018-09-26 02:57
I provide my information, node-v 10.9.0 x64 ~ npm-v 6.4.1 ~ ionic -v 4.12 ~ wind 10 ~

Create a new ionic4+angular6 project, package directly to android, Web View failed to load

**Comment by SmallProgramIndustry** [comment] 2018-09-28 03:34
@somq run android OK？

**Comment by somq** [comment] 2018-09-28 07:31
@SmallProgramIndustry Yes it works with ```<base href="." />``` but I wonder if it does not break the router. It does not seem for now at least...

**Comment by samzhao2008** [comment] 2018-10-06 00:11
I had the same issues today when I plugged my android phone and run `ionic cordova run android`, it didn't work on my galaxy s8 plus with android version 7.0.  A blank page showed, nothing else happened. The error message varied each time: 
1. Failed to load resources error, basically all the js files not found.
2. async function error in vendor.js.

I used cordova-android 6.0, It seems upgrade codova-android would work, at least it worked for me. No js files not found error, no blank screen forever, no error found in vendor.js. 

`Ionic:

   ionic (Ionic CLI)             : 4.2.1 (/Users/yzhao/.nvm/versions/node/v10.9.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.7
   @angular-devkit/build-angular : 0.7.5
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 6.1.5
   @ionic/angular-toolkit        : not installed

Cordova:

   cordova (Cordova CLI) : 8.1.1 (cordova-lib@8.1.0)
   Cordova Platforms     : android 7.1.0, browser 5.0.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.1.4, (and 9 other plugins)

System:

   ios-sim : 5.0.6
   NodeJS  : v10.9.0 (/Users/yzhao/.nvm/versions/node/v10.9.0/bin/node)
   npm     : 6.2.0
   OS      : macOS Sierra
   Xcode   : Xcode 8.3.1 Build version 8E1000a`

**Comment by somq** [comment] 2018-10-08 16:31
https://github.com/ionic-team/ionic-cli/issues/3530

**Comment by andrewg211** [comment] 2018-10-24 23:05
Any work on a fix for this?

**Comment by somq** [comment] 2018-10-25 07:37
A temporary fix is to set `<base href="." />` in index.html

**Comment by danielehrhardt** [comment] 2018-11-12 02:15
Same Issue here

**Comment by MoacirSchmidt** [comment] 2018-11-12 03:34
1) this error occurs only with cordova-plugin-ionic-webview 1

2) Setting  <base href="." /> in index.html causes images not to be load.

**Comment by pjc0247** [comment] 2018-12-07 04:43
`<base href="." />` is not a solution.

**Comment by BertHcoder** [comment] 2018-12-07 14:42
Same problem :s

**Comment by BertHcoder** [comment] 2018-12-07 14:54
I found a fix !!
search your solution for base href
than pick the index.html file and change the base href ./  to <base href="/android_asset/www/">
delete your app on the phone and re run android fixed it for me

problem is cause by angular cli dit te plaatsen

**Comment by pjc0247** [comment] 2018-12-10 05:46
@dwieeb It works well on browsers.
Try `android` build. (Same in `ios` in my case)

**Comment by pjc0247** [comment] 2018-12-10 06:02
![image](https://user-images.githubusercontent.com/1961216/49713541-857d4300-fc8c-11e8-900c-186601b06a02.png)

Here is the problem. 
Every path is wrong execept `index.html`.

**Comment by pjc0247** [comment] 2018-12-10 06:04
![image](https://user-images.githubusercontent.com/1961216/49713602-d0975600-fc8c-11e8-980a-141ce20964ae.png)

`<base href="." />` cannot be a solution because they make another javascript exceptions.
And also not working with `css` (url).

**Comment by JunusErgin** [comment] 2018-12-20 14:42
Hey Ionic-team team,

i'm having the same problem. I'm going to share my system Info with you. 

```
$ ionic info
√ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)          : 4.6.0
    "@ionic-native/core": "5.0.0-beta.21",
    "@ionic-native/splash-screen": "5.0.0-beta.21",
    "@ionic-native/status-bar": "5.0.0-beta.21",
    "@ionic/angular": "4.0.0-rc.0",

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.7
@angular-devkit/build-angular     0.10.7
@angular-devkit/build-optimizer   0.10.7
@angular-devkit/build-webpack     0.10.7
@angular-devkit/core              7.0.7
@angular-devkit/schematics        7.0.7
@angular/cli                      7.0.7
@ngtools/webpack                  7.0.7
@schematics/angular               7.0.7
@schematics/update                0.10.7
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1


Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : android 6.3.0
   Cordova Plugins       : 
    "cordova-android": "6.3.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-ionic-keyboard": "^2.1.3",
    "cordova-plugin-ionic-webview": "^2.3.1",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",

System:
   NodeJS : v10.14.1
   npm    : 6.4.1
   OS     : Windows 10
```

Hope that helps!
Junus

**Comment by coreyhub** [comment] 2018-12-26 22:00
I found a fix and it works my end. 
In the index.html, change base href="/"  to  base href="./" 

This is what ionic info brings back:

Ionic:

   ionic (Ionic CLI)             : 4.6.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : android 6.3.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 4 other plugins)

System:

   ios-deploy : 1.9.2
   ios-sim    : 5.0.3
   NodeJS     : v7.9.0 (/usr/local/Cellar/node/7.9.0/bin/node)
   npm        : 5.8.0
   OS         : macOS Sierra
   Xcode      : Xcode 9.2 Build version 9C40b

**Comment by aksish007** [comment] 2019-01-04 10:44
@coreyhub 
Changing base href="/" to base href="./" also doesn't work. Icons stopped loading after that.

**Comment by laggonzalez** [comment] 2019-01-04 13:58
Same problem.
It works on the explorer but not in native (both iOS and Android).
If I "chrome://inspect" the native app, it clearly says that it cannot find the js files.
If I change to to href="." or "./", the css and image assets are not found.
If I install cordova-plugin-ionic-webview, the same.
Following the instructions on https://github.com/ionic-team/ionic-cli/issues/3530, the same.

I am tempted to downgrade to Ionic 3... 
Has anyone tried something else?

**Comment by aksish007** [comment] 2019-01-06 17:35
> Same problem.
> It works on the explorer but not in native (both iOS and Android).
> If I "chrome://inspect" the native app, it clearly says that it cannot find the js files.
> If I change to to href="." or "./", the css and image assets are not found.
> If I install cordova-plugin-ionic-webview, the same.
> Following the instructions on [ionic-team/ionic-cli#3530](https://github.com/ionic-team/ionic-cli/issues/3530), the same.
> 
> I am tempted to downgrade to Ionic 3...
> Has anyone tried something else?

Whats's your local ionic version??

**Comment by bubigen** [comment] 2019-01-08 03:32
@coreyhub  I tried the fix, but it didn't work for me.

@aksish007  If you were able to fix, can you please provide the ionic info here so as to know what versions you use to get success.
Tried updating cordova-plugin-ionic-webview, but unfortunately my cordova-android is 6.2.3 but should be 6.4+. Not sure if updating cordova-android could solve or create any new incompatibilities. 

Here is my Ionic Info:
Ionic:

   ionic (Ionic CLI)             : 4.6.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 7.0.1
   Cordova Platforms     : android 6.2.3
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.0.0, (and 5 other plugins)

System:

   Android SDK Tools : 26.1.1 
   NodeJS            : v10.5.0 (/usr/local/bin/node)
   npm               : 6.5.0
   OS                : Linux 4.15

**Comment by laggonzalez** [comment] 2019-01-08 07:00
> > Same problem.
> > It works on the explorer but not in native (both iOS and Android).
> > If I "chrome://inspect" the native app, it clearly says that it cannot find the js files.
> > If I change to to href="." or "./", the css and image assets are not found.
> > If I install cordova-plugin-ionic-webview, the same.
> > Following the instructions on [ionic-team/ionic-cli#3530](https://github.com/ionic-team/ionic-cli/issues/3530), the same.
> > I am tempted to downgrade to Ionic 3...
> > Has anyone tried something else?
> 
> Whats's your local ionic version??

ionic -v -> 4.2.1
cordova -v -> 8.1.2
Thanks.

**Comment by jpozorio** [comment] 2019-01-11 22:32
I solve my problem after update ionic cli from `4.6.1` to `4.7.0`
And `cordova-plugin-ionic-webview` to `3.0.0` (latest)

**Comment by pjc0247** [comment] 2019-01-12 13:56
everything is not working with my existing project.
(`cli 4.7.1`, `web view 3.0.0`, `Cordova 8.1.2` and re-install plugins & modules)

however new project works fine. I don't know why.

**Closed** 2019-01-29 20:48 UTC
Labels: triage

**Comment by dadagov125** [comment] 2019-02-01 21:46
my solution:
1 ```ionic cordova platform remove android```
2 ```ionic cordova platform add android@7.1.0```
3 ```ionic cordova plugin remove cordova-plugin-ionic-webview```
4 ```ionic cordova plugin add cordova-plugin-ionic-webview@latest```

**Comment by ctraCoding** [comment] 2019-02-16 06:00
> my solution:
> 1 `ionic cordova platform remove android`
> 2 `ionic cordova platform add android@7.1.0`
> 3 `ionic cordova plugin remove cordova-plugin-ionic-webview`
> 4 `ionic cordova plugin add cordova-plugin-ionic-webview@latest`

this fixed the problem! Please save time eyeryone and do step 1 - 2... trying every solution here and only this fix it ! :-) Ty!

**Comment by andrewg211** [comment] 2019-02-16 06:22
Thanks for solutions, @mhartington although this issue is resolved (solutions posted after being closed), can you please not close issues until a solution has been posted. Thank you

**Comment by NiklasMerz** [comment] 2019-02-20 20:12
This is still a problem if you use capacitor and electron.

**Comment by cvaliere** [comment] 2019-02-28 09:07
does that mean that Ionic 4 doesn't work on Android, except if you install cordova-plugin-ionic-webview?

**Comment by ChristianEGB** [comment] 2019-03-08 00:18
The solution that @dadagov125 provided worked for me too.

**Comment by patryk-fuhrman** [comment] 2019-04-01 08:43
The solution of @dadagov125 is not working for me. Any ideas when it will be fixed?

**Comment by pjc0247** [comment] 2019-04-01 09:49
@patryk-fuhrman Just update everything related with ionic/cordova and test with blank project.

**Comment by ChristianEGB** [comment] 2019-04-01 16:36
@patryk-fuhrman as @pjc0247 update everything, that should work

**Comment by patryk-fuhrman** [comment] 2019-04-02 08:52
@pjc0247 @ChristianEGB right, now it works, thanks guys!

**Comment by Belgarat** [comment] 2019-04-11 07:29
Right, it works, thanks!
you saved my life! :100:

**Comment by danielrf121** [comment] 2019-04-19 02:12
> my solution:
> 1 `ionic cordova platform remove android`
> 2 `ionic cordova platform add android@7.1.0`
> 3 `ionic cordova plugin remove cordova-plugin-ionic-webview`
> 4 `ionic cordova plugin add cordova-plugin-ionic-webview@latest`

Thanks!

**Comment by daraul** [comment] 2019-05-13 17:15
I encountered this error on Friday, after spending a week and a half upgrading my biggest ionic 3 application. 

The [steps outlined here](https://github.com/ionic-team/starters/issues/451#issuecomment-459878855) didn't work.

@mhartington can you tell me why this was closed? Is there an official response here? Should I use ionic pro to build my application?

**Comment by layinka** [comment] 2019-05-23 07:04
i can confirm the steps outlined above don't work too.
Please is there an official fix?

**Comment by bigshowbp01** [comment] 2019-05-28 04:28
> my solution:
> 1 `ionic cordova platform remove android`
> 2 `ionic cordova platform add android@7.1.0`
> 3 `ionic cordova plugin remove cordova-plugin-ionic-webview`
> 4 `ionic cordova plugin add cordova-plugin-ionic-webview@latest`

Thank so much this solution is real fix my issue 
thai language is cal "ขอบคุณครับ" KOB KHUN KLAB

**Comment by JeongJun-Lee** [comment] 2019-06-06 12:11
Should be reopened. Becauase same issue with android@8.0 and cordova-plugin-ionic-webview 4.0.1

**Comment by ChristianEGB** [comment] 2019-06-06 15:43
Hi @layinka @daraul can you give more information about in which android version are you trying to fix the issue? I found by my self that android 8 into ionic have a lot of changes. My point here is to know if you really want to continue developing with android 8 as the target version since Oreo (Android 8) DOES NOT HAVE a complete use right now, I think that you should start from Android 6 or 7. The steps listed above worked for me. Right now I am running everything in Android 7. Please see the steps listed below if you want to change from Android 8 to Android 7, Indeed, when you develop a new application from Android Studio the IDE tells you that you should use Android 7 as the target version because right now not everyone is using Android 8.

To change from Android 8 to 7 and fix problem at the same time:

`ionic cordova platform remove android@^8.0.0
ionic cordova platform remove android
ionic cordova platform add android@7.1.0
ionic cordova plugin remove cordova-plugin-ionic-webview
ionic cordova plugin add cordova-plugin-ionic-webview@latest`

At the end you can run

`ionic cordova run android` to check if it runs on your device

Regards.

**Comment by daraul** [comment] 2019-06-06 17:23
I had tried android 8 and 7.0 I believe, @ChristianEGB. I'll try again and report my findings.

**Comment by ChristianEGB** [comment] 2019-06-12 18:29
Hi @daraul how was it, did it worked?

Regards.

**Comment by MiguelSyll** [comment] 2019-06-28 08:38
I have this problem. Is there some official solution for this problem?

**Comment by ChristianEGB** [comment] 2019-06-28 18:06
Hi @MiguelSyll can you please see my last update. A lot of people said that this worked perfectly, please try and let me know if don't. Also please provide more information about the environment that you are running, Android version, etc.

Regards.

> Hi @layinka @daraul can you give more information about in which android version are you trying to fix the issue? I found by my self that android 8 into ionic have a lot of changes. My point here is to know if you really want to continue developing with android 8 as the target version (if this is the case), since Oreo (Android 8) DOES NOT HAVE a complete use right now, I think that you should start from Android 6 or 7. The steps listed above worked for me. Right now I am running everything in Android 7. Please see the steps listed below if you want to change from Android 8 to Android 7, Indeed, when you develop a new application from Android Studio the IDE tells you that you should use Android 7 as the target version because right now not everyone is using Android 8.
> 
> To change from Android 8 to 7 and fix the problem at the same time:
> 
> `ionic cordova platform remove android@^8.0.0`
> `ionic cordova platform remove android`
> `ionic cordova platform add android@7.1.0`
> `ionic cordova plugin remove cordova-plugin-ionic-webview`
> `ionic cordova plugin add cordova-plugin-ionic-webview@latest`
> 
> At the end you can run
> 
> `ionic cordova run android` to check if it runs on your device
> 
> Regards.

**Comment by zimprince** [comment] 2019-07-11 08:27
> my solution:
> 1 `ionic cordova platform remove android`
> 2 `ionic cordova platform add android@7.1.0`
> 3 `ionic cordova plugin remove cordova-plugin-ionic-webview`
> 4 `ionic cordova plugin add cordova-plugin-ionic-webview@latest`

I can vouch for this solution. And don't forget to add the plugin in your config.xml

**Comment by cvaliere** [comment] 2019-07-11 10:45
my question still remains: does that mean that Ionic 4 doesn't work on Android, except if you install cordova-plugin-ionic-webview?

**Comment by ChristianEGB** [comment] 2019-07-11 13:38
@cvaliere you can answer your own question, try something new, let say, uninstall the web view and everything else, repeat the steps that we gave but without the step of the installation of webview, then try to run everything and please share with us the results, that would be awesome.

**Comment by cvaliere** [comment] 2019-07-11 13:54
the result is that it fails, of course, otherwise I wouldn't be sparing my time on this thread...

**Comment by ChristianEGB** [comment] 2019-07-11 13:56
@cvaliere there you go.

**Comment by cvaliere** [comment] 2019-07-11 14:39
and it doesn't bother you?
say, for instance, that:
- this Ionic WebView plugin, which is originally a fork of the WKWebView plugin (which is still maintained and is perfectly fine: https://github.com/apache/cordova-plugin-wkwebview-engine), has always been optional (until Ionic 4), and nowhere in the docs it is written that it is now mandatory
- it currently has 101 issues on its github repository, so it would be completely legit to prefer using another one
- the current version of that plugin only supports iOS11+, which may be a blocker for some developers (I know, you can always use v2+ of the plugin, but you have to know it, it's written nowhere)

then, you can think: "ok, all these people who didn't install that plugin are just stupid, it's **obvious** that it is mandatory even if it's written nowhere; and if they want to support iOS10, it's **obvious** that they have to downgrade the plugin even if it's written nowhere; and if they were using another WKWebView plugin, well, they can't anymore, but it's **obvious** and **perfectly fine**"

it happens that I don't think it is obvious nor perfectly fine; please don't disrespect me for that :)

**Comment by ChristianEGB** [comment] 2019-07-11 15:33
@cvaliere I think that you're right but maybe it depends on the state of your application, are you developing a newer app? do you want to move from V3 to V4? in which versions of Android/iOS do you want to build your app? this are some common questions that you have to question your self before to get started with Ionic V4, I am not a person who defends the idea to use web view instead of Native UI but it is known that Ionic V4 uses web view. In my case I am developing an app where in my plans would be deployed for Android 7 or 8, maybe 6 too but in this case I am not thinking to release anything into iOS, as you can see my answer is just for Android. As I said, your comment is perfectly right but you have to choose wisely the version of ionic that you have to use depending of the ideas that you have with your app and also you have to think first if you want to build your app with Ionic, is this the best framework for my app?

And obviously I will not disrespect you for anything.
Regards.

Some info about the idea [here](https://www.joshmorony.com/the-biggest-advantage-of-ionic-applications-web-views/)

**Comment by rdai** [comment] 2019-08-31 16:11
I came here because my new test app with Ionic 4 + [Videogular2](https://github.com/videogular/videogular2) works in my older phone and emulator but not Samsung Galaxy S9 for some reason. 

danielrf121 solution made it now work everywhere. However, now I can't install firebase-analytics (and I am assuming I would have issue with other plugins as well) because 

`Plugin doesn't support this project's cordova-android version. cordova-android: 7.1.0, failed version requirement: >=8.0.0`

so changing the android version solved the webview problem but causes a host of other issues, and therefore not the ideal solution long term. 

Is there an update? Is it reasonable to start over and develop on Ionic 4 and hope the webview problem will be addressed later?

Thanks
Ray

**Comment by ChristianEGB** [comment] 2019-08-31 16:29
After moths of develop, and the first version of my app out I decided to write the version two of my application over the native language, this is just my opinion here, and I would like to share this with everyone, many ionic applications have problems visualizing so many functionalities of the native behaviors of the applications, what I can tell you is that in less than 1 month I reach a lot of objectives with the V2 of my application, in less than 1 month I achieve almost all the functionalities of the V1 of my application, I know that we write hybrid apps to get things done in various OS but this open the door to so many problems just to figure out how to do things that native apps do in an easy way, in my experience at the end of the ionic app, I feel that was a Frankenstein-like app and that was not a good feeling for my team and for me, right now we formalize an Android team that have working awesome and a iOS team that its learning but at the end they are reaching every goal.

As I said, this is my opinion, this is just the way that I performed the develop of my app right now.

Regards.

**Comment by FernetB** [comment] 2019-09-23 13:16
> my question still remains: does that mean that Ionic 4 doesn't work on Android, except if you install cordova-plugin-ionic-webview?

Yes and no, you have a misunderstood in the concepts of ionic and cordova. Let me explain.

Ionic framework provides a core of UI components that are responsive for the differents sizes.

Now cordova, or capacitor are in charge of build your app to an android or ios app.

Ionic alone does not build your app into an android or ios. it is just a framework with ui components and a CLI.

**Comment by cvaliere** [comment] 2019-09-30 13:42
@FernetB thank you for your explanations. Though, I've been working with Ionic for 6 years now, since it's in beta version (before Ionic 1), so I pretty well understand the concepts :)

Ionic is indeed "just a framework with ui components and a CLI". But the CLI does *a lot* of things.

A new project built with Cordova CLI does work on Android without any plugin. But a new project built with Ionic CLI doesn't work on Android except if you install `cordova-plugin-ionic-webview`.

My conclusion is that the Ionic CLI configures (or builds) the Android project in a way that makes it dependent on `cordova-plugin-ionic-webview`. What's yours?
