### ISSUE TITLE
feat: New template side menu and tab

### ISSUE THREAD

**Issue by donPuerto** [ionic-team/starters#1683] opened 2021-05-31 12:04 UTC
# Feature Request

**Ionic version:**
Ionic Vue 5

**Describe the Feature Request**
Combine side menu and tab template

**Comment by liamdebeasi** [comment] 2021-08-10 16:57
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/starters/issues/681.

**Closed by liamdebeasi** 2021-08-10 16:57 UTC
Labels: triage
